
on:
  release:
    types: published



name: Upload NPM package

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Set version
        run: |
          echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
        env:
          TAG_NAME: ${{github.event.release.tag_name}}

      #- name: Update version
      #  run: yarn version --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --allow-same-version

      - name: Publish package
        run: yarn publish --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


