name: Upload NPM package

on:
    release:
        types: published

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]
            node-version: [16.x, 18.x]
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'

            - name: yarn install
              run: yarn install

            - name: yarn test
              run: yarn test

            - name: yarn lint
              run: yarn lint

            - name: Set version
              run: |
                  echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
              env:
                  TAG_NAME: ${{github.event.release.tag_name}}

            - name: Update version
              run: yarn version --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --allow-same-version

            - name: Publish package
              run: yarn publish --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
